"""Pydantic API şemaları.

`models/` ORM (DB şekli), `schemas/` API contract — bu ikisi karıştırılmaz
(backend/CLAUDE.md §4).
"""

from app.schemas.auth import (
    AvatarResponse,
    ChangePasswordRequest,
    ChangePasswordResponse,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    LoginRequest,
    MeUpdateRequest,
    ResetPasswordRequest,
    ResetPasswordResponse,
    TokenResponse,
    VerifyResetTokenResponse,
)
from app.schemas.common import SuccessEnvelope
from app.schemas.campaign_detail import (
    CampaignAdMetrics,
    CampaignDailyPoint,
    CampaignDetailResponse,
    CampaignEcomSummary,
    CampaignTopProduct,
)
from app.schemas.dashboard import (
    CampaignAnalysisResponse,
    ChannelAnalysisResponse,
    ChannelDailyPoint,
    ChannelPerformanceRow,
    CohortCell,
    CohortResponse,
    CustomerDailyPoint,
    CustomerFreqBucket,
    CustomerOverviewRow,
    CustomersResponse,
    DimensionBreakdown,
    EcommerceResponse,
    FunnelResponse,
    GoogleAdsResponse,
    MetaAdsResponse,
    NewsletterCompare,
    OverviewResponse,
    ProductsResponse,
    TrafficResponse,
)
from app.schemas.imports import (
    DataTypeColumn,
    DataTypeMeta,
    ImportDetailResponse,
    ImportListItem,
    ImportPreviewResponse,
    ImportPreviewSummary,
    ImportRunResult,
    ImportSampleError,
)
from app.schemas.kpi import (
    CampaignMetric,
    ChannelMetric,
    CustomerTypeRevenue,
    DailySeriesPoint,
    DateRange,
    FunnelStep,
    KPIResult,
    KPISummary,
    TopCustomerRow,
    TopProductRow,
)
from app.schemas.user import MeResponse, RoleSummary, UserResponse

__all__ = [
    "AvatarResponse",
    "CampaignAdMetrics",
    "CampaignAnalysisResponse",
    "CampaignDailyPoint",
    "CampaignDetailResponse",
    "CampaignEcomSummary",
    "CampaignMetric",
    "CampaignTopProduct",
    "ChangePasswordRequest",
    "ChangePasswordResponse",
    "ChannelAnalysisResponse",
    "ChannelDailyPoint",
    "ChannelMetric",
    "ChannelPerformanceRow",
    "CohortCell",
    "CohortResponse",
    "CustomerDailyPoint",
    "CustomerFreqBucket",
    "CustomerOverviewRow",
    "CustomerTypeRevenue",
    "CustomersResponse",
    "DailySeriesPoint",
    "DataTypeColumn",
    "DataTypeMeta",
    "DateRange",
    "DimensionBreakdown",
    "EcommerceResponse",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "FunnelResponse",
    "FunnelStep",
    "GoogleAdsResponse",
    "ImportDetailResponse",
    "ImportListItem",
    "ImportPreviewResponse",
    "ImportPreviewSummary",
    "ImportRunResult",
    "ImportSampleError",
    "KPIResult",
    "KPISummary",
    "LoginRequest",
    "MeResponse",
    "MeUpdateRequest",
    "MetaAdsResponse",
    "NewsletterCompare",
    "OverviewResponse",
    "ProductsResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "RoleSummary",
    "SuccessEnvelope",
    "TokenResponse",
    "TopCustomerRow",
    "TopProductRow",
    "TrafficResponse",
    "UserResponse",
    "VerifyResetTokenResponse",
]
